CREATE TABLE salary_data1 (
	id INTEGER PRIMARY KEY,
	salaryusd INTEGER,
	country TEXT,
	primarydatabase TEXT,
	yearswiththisdatabase INTEGER,
	employmentstatus TEXT,
	jobtitle TEXT,
	managestaff TEXT,
	yearswiththistypeofjob INTEGER,
	otherpeopleonyourteam TEXT,
	databaseservers INTEGER,
	education TEXT,
	educationiscomputerrelated TEXT,
	certifications TEXT,
	hoursworkedperweek INTEGER,
	telecommutedaysperweek TEXT,
	employmentsector TEXT,
	region TEXT
);
